In [1]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.width", 200)

In [2]:
DATA_DIR = Path("systeme_electric")

excel_files = list(DATA_DIR.glob("*.xlsx"))

print(f"Найдено Excel-файлов: {len(excel_files)}")

for file in excel_files:
    print(file.name)

Найдено Excel-файлов: 6
MOQ SystemElectric.xlsx
Динамика продаж_Syseme Electric_2025-2026.xlsx
Ежемесячные остатки SystemElectric 2024-2026.xlsx
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx
Сезонность SystemElectric 2024-2026.xlsx
Товар в пути_SystemElectric на 22.09.2026.xlsx

In [3]:
for file in excel_files:
    print("\n" + "=" * 100)
    print("ФАЙЛ:", file.name)

    xls = pd.ExcelFile(file)

    print("Листы:")
    for sheet in xls.sheet_names:
        print("  -", sheet)

====================================================================================================
ФАЙЛ: MOQ SystemElectric.xlsx
Листы:
  - Лист_1

====================================================================================================
ФАЙЛ: Динамика продаж_Syseme Electric_2025-2026.xlsx
Листы:
  - Лист_1

====================================================================================================
ФАЙЛ: Ежемесячные остатки SystemElectric 2024-2026.xlsx
Листы:
  - Лист_1

====================================================================================================
ФАЙЛ: Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx
Листы:
  - Лист_1
  - Лист1

====================================================================================================
ФАЙЛ: Сезонность SystemElectric 2024-2026.xlsx
Листы:
  - Лист1

====================================================================================================
ФАЙЛ: Товар в пути_SystemElectric на 22.09.2026.xlsx
Листы:
  - TDSheet
  - Лист1

In [4]:
datasets = {}

for file in excel_files:
    xls = pd.ExcelFile(file)

    for sheet in xls.sheet_names:
        key = f"{file.name} | {sheet}"

        try:
            df = pd.read_excel(file, sheet_name=sheet)
            datasets[key] = df

            print(f"{key}: {df.shape[0]} строк × {df.shape[1]} столбцов")

        except Exception as e:
            print(f"ОШИБКА {key}: {e}")

MOQ SystemElectric.xlsx | Лист_1: 556 строк × 5 столбцов
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1: 77313 строк × 8 столбцов
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1: 703 строк × 37 столбцов
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1: 556 строк × 38 столбцов
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1: 22 строк × 15 столбцов
Сезонность SystemElectric 2024-2026.xlsx | Лист1: 22 строк × 15 столбцов
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet: 498 строк × 60 столбцов
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1: 22 строк × 15 столбцов

In [5]:
for name, df in datasets.items():

    print("\n\n")
    print("=" * 120)
    print(name)
    print("=" * 120)

    print("\nРАЗМЕР:")
    print(f"{df.shape[0]} строк × {df.shape[1]} столбцов")

    print("\nСТОЛБЦЫ:")
    for col in df.columns:
        print(f"  - {col}")

    print("\nПЕРВЫЕ 5 СТРОК:")
    display(df.head())

    print("\nТИПЫ ДАННЫХ:")
    display(
        pd.DataFrame({
            "column": df.columns,
            "dtype": df.dtypes.astype(str).values
        })
    )

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1
========================================================================================================================

РАЗМЕР:
556 строк × 5 столбцов

СТОЛБЦЫ:
  - №
  - Номенклатура
  - Номенклатура.Код
  - Артикул
  - Кратность

ПЕРВЫЕ 5 СТРОК:

     №                                                                       Номенклатура Номенклатура.Код        Артикул  Кратность
0  NaN                                                                                NaN              NaN            NaN        NaN
1  1.0   S174  (1кл, инд с/у 16А, IP44) Переключатель "Wessen 59" ВС 616-157Б-18 (60) !!!       030200128_  VS616-157B-18        1.0
2  2.0                          S179   2кл с/у 16А  "Wessen 59" ВС 510-252-18 (10/60) !!!       030200382_   VS510-252-18        1.0
3  3.0         S183  Переключатель 1кл, с инд.,с/у 16А "Wessen 59" ВС 616-157-18 (60) !!!       030200127_   VS616-157-18        1.0
4  4.0                          S184  Диммер (с/у 600Вт) "Wessen 59" ВПП-5С2-18(2/16) !!!       030200141_      SR-5S2-18        1.0

ТИПЫ ДАННЫХ:

             column    dtype
0                 №  float64
1      Номенклатура      str
2  Номенклатура.Код      str
3           Артикул      str
4         Кратность  float64

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1
========================================================================================================================

РАЗМЕР:
77313 строк × 8 столбцов

СТОЛБЦЫ:
  - Дата
  - Номер
  - Документ
  - Код
  - Номенклатура
  - Ед.
  - Склад
  - Количество

ПЕРВЫЕ 5 СТРОК:

                  Дата         Номер                                       Документ         Код                                                                   Номенклатура Ед.   Склад  Количество
0  18.01.2023 16:00:11  2.000000e+10  Расходная накладная 20000004016 от 18.01.2023  300200445_                                   А409 Рамка 5-ная "ATLAS" алюминий ATN305 (5)  шт  Алматы       -10.0
1  09.06.2023 17:29:41  2.000005e+10  Расходная накладная 20000052612 от 09.06.2023  300200299_       S396 Роз. 2-ная с/у 16А с з/к з/ш со сдвиж.крыш."ATLAS" белый ATN128 (6)  шт  Алматы        -2.0
2  17.11.2023 14:51:23  2.000012e+10  Расходная накладная 20000117295 от 17.11.2023  300200290_           S392 Переключ. 1 кл с инд 10А с/у б/рамки  "ATLAS" белый ATN163 (20)  шт  Алматы       -10.0
3  17.11.2023 15:02:40  2.000012e+10  Расходная накладная 20000117283 от 17.11.2023  300200448_     А393 Перекрест. переключ. 1 кл 10А с/у б/рамки "ATLAS" алюминий ATN371 (5)  шт  Алматы        -2.0
4  26.12.2023 17:04:12  2.000013e+10  Расходная накладная 20000132885 от 26.12.2023  020100162_  K077 Перекрест.переключ. 1 кл 10А с/у б/рамки "ATLAS", КАРБОН -  ATN1071 (2)   шт  Алматы        -5.0

ТИПЫ ДАННЫХ:

         column    dtype
0          Дата      str
1         Номер  float64
2      Документ      str
3           Код      str
4  Номенклатура      str
5           Ед.      str
6         Склад      str
7    Количество  float64

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
========================================================================================================================

РАЗМЕР:
703 строк × 37 столбцов

СТОЛБЦЫ:
  - №
  - Номенклатура
  - Номенклатура.Код
  - Ед.изм
  - янв. 2024
  - февр. 2024
  - март 2024
  - апр. 2024
  - май 2024
  - июнь 2024
  - июль 2024
  - авг. 2024
  - сент. 2024
  - окт. 2024
  - нояб. 2024
  - дек. 2024
  - янв. 2025
  - февр. 2025
  - март 2025
  - апр. 2025
  - май 2025
  - июнь 2025
  - июль 2025
  - авг. 2025
  - сент. 2025
  - окт. 2025
  - нояб. 2025
  - дек. 2025
  - янв. 2026
  - февр. 2026
  - март 2026
  - апр. 2026
  - май 2026
  - июнь 2026
  - июль 2026
  - авг. 2026
  - сент. 2026

ПЕРВЫЕ 5 СТРОК:

,№,Номенклатура,Номенклатура.Код,Ед.изм,янв. 2024,февр. 2024,март 2024,апр. 2024,май 2024,июнь 2024,июль 2024,авг. 2024,сент. 2024,окт. 2024,нояб. 2024,дек. 2024,янв. 2025,февр. 2025,март 2025,апр. 2025,май 2025,июнь 2025,июль 2025,авг. 2025,сент. 2025,окт. 2025,нояб. 2025,дек. 2025,янв. 2026,февр. 2026,март 2026,апр. 2026,май 2026,июнь 2026,июль 2026,авг. 2026,сент. 2026
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,"AtlasDesign Розетка 1я Алюминий без з/к без штор. 16А, в сборе, ATN000340 (10)",300200635_,шт,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,"S174 (1кл, инд с/у 16А, IP44) Переключатель ""Wessen 59"" ВС 616-157Б-18 (60) !!!",030200128_,шт,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,5.0,5.0,5.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,"S175 2кл инд с/у 16А ""Wessen 59"" ВС 516-251-18 (10/60)",030200092_,шт,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ТИПЫ ДАННЫХ:

              column    dtype
0                  №  float64
1       Номенклатура      str
2   Номенклатура.Код      str
3             Ед.изм      str
4          янв. 2024  float64
5         февр. 2024  float64
6          март 2024  float64
7          апр. 2024  float64
8           май 2024  float64
9          июнь 2024  float64
10         июль 2024  float64
11         авг. 2024  float64
12        сент. 2024  float64
13         окт. 2024  float64
14        нояб. 2024  float64
15         дек. 2024  float64
16         янв. 2025  float64
17        февр. 2025  float64
18         март 2025  float64
19         апр. 2025  float64
20          май 2025  float64
21         июнь 2025  float64
22         июль 2025  float64
23         авг. 2025  float64
24        сент. 2025  float64
25         окт. 2025  float64
26        нояб. 2025  float64
27         дек. 2025  float64
28         янв. 2026  float64
29        февр. 2026  float64
30         март 2026  float64
31         апр. 2026  float64
32          май 2026  float64
33         июнь 2026  float64
34         июль 2026  float64
35         авг. 2026  float64
36        сент. 2026  float64

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1
========================================================================================================================

РАЗМЕР:
556 строк × 38 столбцов

СТОЛБЦЫ:
  - Номенклатура
  - Номенклатура.Код
  - Артикул
  - Кратность
  - янв. 2024
  - февр. 2024
  - март 2024
  - апр. 2024
  - май 2024
  - июнь 2024
  - июль 2024
  - авг. 2024
  - сент. 2024
  - окт. 2024
  - нояб. 2024
  - дек. 2024
  - янв. 2025
  - февр. 2025
  - март 2025
  - апр. 2025
  - май 2025
  - июнь 2025
  - июль 2025
  - авг. 2025
  - сент. 2025
  - окт. 2025
  - нояб. 2025
  - дек. 2025
  - янв. 2026
  - февр. 2026
  - март 2026
  - апр. 2026
  - май 2026
  - июнь 2026
  - июль 2026
  - авг. 2026
  - сент. 2026
  - Итого

ПЕРВЫЕ 5 СТРОК:

,Номенклатура,Номенклатура.Код,Артикул,Кратность,янв. 2024,февр. 2024,март 2024,апр. 2024,май 2024,июнь 2024,июль 2024,авг. 2024,сент. 2024,окт. 2024,нояб. 2024,дек. 2024,янв. 2025,февр. 2025,март 2025,апр. 2025,май 2025,июнь 2025,июль 2025,авг. 2025,сент. 2025,окт. 2025,нояб. 2025,дек. 2025,янв. 2026,февр. 2026,март 2026,апр. 2026,май 2026,июнь 2026,июль 2026,авг. 2026,сент. 2026,Итого
0,NaN,NaN,NaN,NaN,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество,Количество
1,"S174 (1кл, инд с/у 16А, IP44) Переключатель ""Wessen 59"" ВС 616-157Б-18 (60) !!!",030200128_,VS616-157B-18,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,"S179 2кл с/у 16А ""Wessen 59"" ВС 510-252-18 (10/60) !!!",030200382_,VS510-252-18,0.0,1,4,1,1,9,4,3,74,-34,5,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,9,NaN,15,8,7,4,19,45,4,5,NaN,4,196
3,"S183 Переключатель 1кл, с инд.,с/у 16А ""Wessen 59"" ВС 616-157-18 (60) !!!",030200127_,VS616-157-18,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,"S184 Диммер (с/у 600Вт) ""Wessen 59"" ВПП-5С2-18(2/16) !!!",030200141_,SR-5S2-18,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18

ТИПЫ ДАННЫХ:

              column    dtype
0       Номенклатура      str
1   Номенклатура.Код      str
2            Артикул      str
3          Кратность  float64
4          янв. 2024   object
5         февр. 2024   object
6          март 2024   object
7          апр. 2024   object
8           май 2024   object
9          июнь 2024   object
10         июль 2024   object
11         авг. 2024   object
12        сент. 2024   object
13         окт. 2024   object
14        нояб. 2024   object
15         дек. 2024   object
16         янв. 2025   object
17        февр. 2025   object
18         март 2025   object
19         апр. 2025   object
20          май 2025   object
21         июнь 2025   object
22         июль 2025   object
23         авг. 2025   object
24        сент. 2025   object
25         окт. 2025   object
26        нояб. 2025   object
27         дек. 2025   object
28         янв. 2026   object
29        февр. 2026   object
30         март 2026   object
31         апр. 2026   object
32          май 2026   object
33         июнь 2026   object
34         июль 2026   object
35         авг. 2026   object
36        сент. 2026   object
37             Итого   object

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
========================================================================================================================

РАЗМЕР:
22 строк × 15 столбцов

СТОЛБЦЫ:
  - Unnamed: 0
  - Unnamed: 1
  - Unnamed: 2
  - Unnamed: 3
  - Unnamed: 4
  - Unnamed: 5
  - Unnamed: 6
  - Unnamed: 7
  - Unnamed: 8
  - Unnamed: 9
  - Unnamed: 10
  - Unnamed: 11
  - Unnamed: 12
  - Unnamed: 13
  - Unnamed: 14

ПЕРВЫЕ 5 СТРОК:

  Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3   Unnamed: 4 Unnamed: 5 Unnamed: 6   Unnamed: 7   Unnamed: 8   Unnamed: 9 Unnamed: 10 Unnamed: 11  Unnamed: 12   Unnamed: 13 Unnamed: 14
0        NaN        NaN        NaN          NaN          NaN        NaN        NaN          NaN          NaN          NaN         NaN         NaN          NaN           NaN         NaN
1        год        янв        фев          мар          апр        май        июн          июл          авг          сен         окт         ноя          дек         ИТОГО         NaN
2       2024   24596427   22395512     44147660  62276496.32   73462110   68345412  71289315.98  91399515.64     99082123    88432469    82883679     65881945  794192664.94         NaN
3       2025   60612221   70526214   62394638.9  80289436.03   77227054   80386586  79580845.35  85147826.95     75393744    70827551    72949510  71608529.44  886944156.67         NaN
4       2026   51463402   57127585  49906664.43     61255146   59215517   68110627  72110849.17  70105174.18  45371784.46         NaN         NaN          NaN  534666749.24         NaN

ТИПЫ ДАННЫХ:

         column   dtype
0    Unnamed: 0  object
1    Unnamed: 1  object
2    Unnamed: 2  object
3    Unnamed: 3  object
4    Unnamed: 4  object
5    Unnamed: 5  object
6    Unnamed: 6  object
7    Unnamed: 7  object
8    Unnamed: 8  object
9    Unnamed: 9  object
10  Unnamed: 10  object
11  Unnamed: 11  object
12  Unnamed: 12  object
13  Unnamed: 13  object
14  Unnamed: 14  object

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1
========================================================================================================================

РАЗМЕР:
22 строк × 15 столбцов

СТОЛБЦЫ:
  - Unnamed: 0
  - Unnamed: 1
  - Unnamed: 2
  - Unnamed: 3
  - Unnamed: 4
  - Unnamed: 5
  - Unnamed: 6
  - Unnamed: 7
  - Unnamed: 8
  - Unnamed: 9
  - Unnamed: 10
  - Unnamed: 11
  - Unnamed: 12
  - Unnamed: 13
  - Unnamed: 14

ПЕРВЫЕ 5 СТРОК:

  Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3   Unnamed: 4 Unnamed: 5 Unnamed: 6   Unnamed: 7   Unnamed: 8   Unnamed: 9 Unnamed: 10 Unnamed: 11  Unnamed: 12   Unnamed: 13 Unnamed: 14
0        NaN        NaN        NaN          NaN          NaN        NaN        NaN          NaN          NaN          NaN         NaN         NaN          NaN           NaN         NaN
1        год        янв        фев          мар          апр        май        июн          июл          авг          сен         окт         ноя          дек         ИТОГО         NaN
2       2024   24596427   22395512     44147660  62276496.32   73462110   68345412  71289315.98  91399515.64     99082123    88432469    82883679     65881945  794192664.94         NaN
3       2025   60612221   70526214   62394638.9  80289436.03   77227054   80386586  79580845.35  85147826.95     75393744    70827551    72949510  71608529.44  886944156.67         NaN
4       2026   51463402   57127585  49906664.43     61255146   59215517   68110627  72110849.17  70105174.18  45371784.46         NaN         NaN          NaN  534666749.24         NaN

ТИПЫ ДАННЫХ:

         column   dtype
0    Unnamed: 0  object
1    Unnamed: 1  object
2    Unnamed: 2  object
3    Unnamed: 3  object
4    Unnamed: 4  object
5    Unnamed: 5  object
6    Unnamed: 6  object
7    Unnamed: 7  object
8    Unnamed: 8  object
9    Unnamed: 9  object
10  Unnamed: 10  object
11  Unnamed: 11  object
12  Unnamed: 12  object
13  Unnamed: 13  object
14  Unnamed: 14  object

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
========================================================================================================================

РАЗМЕР:
498 строк × 60 столбцов

СТОЛБЦЫ:
  - Unnamed: 0
  - Unnamed: 1
  - Unnamed: 2
  - Unnamed: 3
  - Unnamed: 4
  - Unnamed: 5
  - Unnamed: 6
  - Unnamed: 7
  - Unnamed: 8
  - Unnamed: 9
  - Unnamed: 10
  - Unnamed: 11
  - Unnamed: 12
  - Unnamed: 13
  - Unnamed: 14
  - Unnamed: 15
  - Unnamed: 16
  - Unnamed: 17
  - Unnamed: 18
  - Unnamed: 19
  - Unnamed: 20
  - Unnamed: 21
  - Unnamed: 22
  - Unnamed: 23
  - Unnamed: 24
  - Unnamed: 25
  - Unnamed: 26
  - Unnamed: 27
  - Unnamed: 28
  - Unnamed: 29
  - Unnamed: 30
  - Unnamed: 31
  - Unnamed: 32
  - Unnamed: 33
  - Unnamed: 34
  - Unnamed: 35
  - Unnamed: 36
  - Unnamed: 37
  - Unnamed: 38
  - Unnamed: 39
  - Unnamed: 40
  - Unnamed: 41
  - Unnamed: 42
  - Unnamed: 43
  - Unnamed: 44
  - СКЛАДЫ
  - Unnamed: 46
  - Unnamed: 47
  - Unnamed: 48
  - Unnamed: 49
  - Unnamed: 50
  - Unnamed: 51
  - Unnamed: 52
  - Unnamed: 53
  - Unnamed: 54
  - Unnamed: 55
  - Unnamed: 56
  - Unnamed: 57
  - Unnamed: 58
  - Unnamed: 59

ПЕРВЫЕ 5 СТРОК:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,СКЛАДЫ,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,№,Артикул поставщика,Код 1с,Наименование,Категория 2026,СС реал,Январь 2024 г.,Февраль 2024 г.,Март 2024 г.,Апрель 2024 г.,Май 2024 г.,Июнь 2024 г.,Июль 2024 г.,Август 2024 г.,Сентябрь 2024 г.,Октябрь 2024 г.,Ноябрь 2024 г.,Декабрь 2024 г.,Продажи 2024,Ср мес 2024,Январь 2025 г.,Февраль 2025 г.,Март 2025 г.,Апрель 2025 г.,Май 2025 г.,Июнь 2025 г.,Июль 2025 г.,Август 2025 г.,Сентябрь 2025 г.,Октябрь 2025 г.,Ноябрь 2025 г.,Декабрь 2025 г.,Январь 2026 г.,Февраль 2026 г.,Март 2026 г.,Апрель 2026 г.,Май 2026 г.,Июнь 2026 г.,Июль 2026 г.,Август 2026 г.,Сентябрь 2026 г.,Сумма последние 12 мес,Ср мес за последние 12 мес,Кэф. Роста,Кэф. Сез-ти,Витрина,Остаток ТЗ,РЦ ЕКТ Рыскулова,Розничный склад,Остаток,Зарезервировано,Свободный остаток,Запас,Заказ,СЭ в пути 24.09,NaN,NaN,NaN,NaN,Вес
1,1,ATN000343,300200428_,"A398 Роз. с з/к 16А с/у б/рамки ""ATLAS"" алюминий ATN343 (10)",1,1050.61,346,335,233,525,546,541,508,707,359,384,253,530,5267,438.916667,610,394,444,104,589,413,379,170,806,212,353,724,111,152,380,209,122,310,135,124,135,3773,314.416667,-0.408524,0.425156,0,6,0,50,1118,0,1118,3.733899,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2,ATN000333,300200442_,"A404 USB розетка - 2 порта с/у б/рамки ""ATLAS"" алюминий ATN333 (1)",7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,3,ATN000330,ATN000330,"SO + USB РОЗЕТКА A+A, 5В/2,4А, 2х5В/1,2А, механизм ""ATLAS"" алюминий ATN330",7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,4,ATN000312,300200430_,"А384 Выкл 1 кл 10А с/у ""ATLAS"" алюминий ATN312 (10)",2,1286.15,94,40,26,25,119,62,26,24,29,26,70,-23,518,43.166667,32,15,3,20,25,100,12,12,42,23,18,132,25,6,24,9,15,25,25,31,22,397,33.083333,-0.346774,-0.330645,0,1,0,17,76,0,76,2.84131,NaN,0,NaN,NaN,NaN,NaN,NaN

ТИПЫ ДАННЫХ:

         column    dtype
0    Unnamed: 0   object
1    Unnamed: 1      str
2    Unnamed: 2      str
3    Unnamed: 3      str
4    Unnamed: 4   object
5    Unnamed: 5   object
6    Unnamed: 6   object
7    Unnamed: 7   object
8    Unnamed: 8   object
9    Unnamed: 9   object
10  Unnamed: 10   object
11  Unnamed: 11   object
12  Unnamed: 12   object
13  Unnamed: 13   object
14  Unnamed: 14   object
15  Unnamed: 15   object
16  Unnamed: 16   object
17  Unnamed: 17   object
18  Unnamed: 18   object
19  Unnamed: 19   object
20  Unnamed: 20   object
21  Unnamed: 21   object
22  Unnamed: 22   object
23  Unnamed: 23   object
24  Unnamed: 24   object
25  Unnamed: 25   object
26  Unnamed: 26   object
27  Unnamed: 27   object
28  Unnamed: 28   object
29  Unnamed: 29   object
30  Unnamed: 30   object
31  Unnamed: 31   object
32  Unnamed: 32   object
33  Unnamed: 33   object
34  Unnamed: 34   object
35  Unnamed: 35   object
36  Unnamed: 36   object
37  Unnamed: 37   object
38  Unnamed: 38   object
39  Unnamed: 39   object
40  Unnamed: 40   object
41  Unnamed: 41   object
42  Unnamed: 42   object
43  Unnamed: 43   object
44  Unnamed: 44   object
45       СКЛАДЫ   object
46  Unnamed: 46   object
47  Unnamed: 47   object
48  Unnamed: 48   object
49  Unnamed: 49   object
50  Unnamed: 50   object
51  Unnamed: 51   object
52  Unnamed: 52   object
53  Unnamed: 53      str
54  Unnamed: 54   object
55  Unnamed: 55  float64
56  Unnamed: 56  float64
57  Unnamed: 57  float64
58  Unnamed: 58  float64
59  Unnamed: 59      str

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1
========================================================================================================================

РАЗМЕР:
22 строк × 15 столбцов

СТОЛБЦЫ:
  - Unnamed: 0
  - Unnamed: 1
  - Unnamed: 2
  - Unnamed: 3
  - Unnamed: 4
  - Unnamed: 5
  - Unnamed: 6
  - Unnamed: 7
  - Unnamed: 8
  - Unnamed: 9
  - Unnamed: 10
  - Unnamed: 11
  - Unnamed: 12
  - Unnamed: 13
  - Unnamed: 14

ПЕРВЫЕ 5 СТРОК:

  Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3   Unnamed: 4 Unnamed: 5 Unnamed: 6   Unnamed: 7   Unnamed: 8   Unnamed: 9 Unnamed: 10 Unnamed: 11  Unnamed: 12   Unnamed: 13 Unnamed: 14
0        NaN        NaN        NaN          NaN          NaN        NaN        NaN          NaN          NaN          NaN         NaN         NaN          NaN           NaN         NaN
1        год        янв        фев          мар          апр        май        июн          июл          авг          сен         окт         ноя          дек         ИТОГО         NaN
2       2024   24596427   22395512     44147660  62276496.32   73462110   68345412  71289315.98  91399515.64     99082123    88432469    82883679     65881945  794192664.94         NaN
3       2025   60612221   70526214   62394638.9  80289436.03   77227054   80386586  79580845.35  85147826.95     75393744    70827551    72949510  71608529.44  886944156.67         NaN
4       2026   51463402   57127585  49906664.43     61255146   59215517   68110627  72110849.17  70105174.18  45371784.46         NaN         NaN          NaN  534666749.24         NaN

ТИПЫ ДАННЫХ:

         column   dtype
0    Unnamed: 0  object
1    Unnamed: 1  object
2    Unnamed: 2  object
3    Unnamed: 3  object
4    Unnamed: 4  object
5    Unnamed: 5  object
6    Unnamed: 6  object
7    Unnamed: 7  object
8    Unnamed: 8  object
9    Unnamed: 9  object
10  Unnamed: 10  object
11  Unnamed: 11  object
12  Unnamed: 12  object
13  Unnamed: 13  object
14  Unnamed: 14  object

In [6]:
for name, df in datasets.items():

    print("\n" + "=" * 120)
    print(name)

    missing = pd.DataFrame({
        "missing_count": df.isna().sum(),
        "missing_percent": (df.isna().mean() * 100).round(2)
    })

    missing = missing[missing["missing_count"] > 0]
    missing = missing.sort_values("missing_percent", ascending=False)

    print("\nПРОПУСКИ:")

    if len(missing) == 0:
        print("Пропусков нет")
    else:
        display(missing)

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1

ПРОПУСКИ:

                  missing_count  missing_percent
№                             2             0.36
Номенклатура.Код              2             0.36
Артикул                       2             0.36
Кратность                     2             0.36
Номенклатура                  1             0.18

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1

ПРОПУСКИ:

              missing_count  missing_percent
Количество               13             0.02
Документ                  1             0.00
Номер                     1             0.00
Код                       1             0.00
Номенклатура              1             0.00
Ед.                       1             0.00
Склад                     1             0.00

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1

ПРОПУСКИ:

                  missing_count  missing_percent
февр. 2024                  346            49.22
март 2024                   337            47.94
янв. 2024                   337            47.94
апр. 2024                   333            47.37
май 2024                    330            46.94
июнь 2024                   321            45.66
июль 2024                   319            45.38
авг. 2024                   228            32.43
авг. 2026                   138            19.63
сент. 2026                  137            19.49
июнь 2026                   136            19.35
март 2026                   134            19.06
апр. 2026                   134            19.06
июль 2026                   133            18.92
май 2026                    130            18.49
февр. 2026                  129            18.35
янв. 2026                   128            18.21
дек. 2025                   126            17.92
апр. 2025                   115            16.36
февр. 2025                  111            15.79
март 2025                   111            15.79
май 2025                    106            15.08
нояб. 2025                  102            14.51
июнь 2025                    92            13.09
сент. 2025                   91            12.94
июль 2025                    91            12.94
окт. 2025                    91            12.94
авг. 2025                    89            12.66
сент. 2024                   83            11.81
окт. 2024                    73            10.38
нояб. 2024                   61             8.68
дек. 2024                    55             7.82
янв. 2025                    52             7.40
Ед.изм                        2             0.28
Номенклатура.Код              2             0.28
Номенклатура                  2             0.28
№                             2             0.28

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

ПРОПУСКИ:

                  missing_count  missing_percent
янв. 2024                   331            59.53
февр. 2024                  318            57.19
март 2024                   286            51.44
июль 2024                   268            48.20
апр. 2024                   268            48.20
май 2024                    266            47.84
июнь 2024                   261            46.94
янв. 2026                   243            43.71
май 2026                    239            42.99
сент. 2026                  238            42.81
февр. 2026                  237            42.63
апр. 2026                   232            41.73
июль 2026                   229            41.19
июнь 2026                   222            39.93
май 2025                    220            39.57
авг. 2026                   205            36.87
март 2025                   205            36.87
июль 2025                   202            36.33
апр. 2025                   199            35.79
июнь 2025                   197            35.43
дек. 2025                   196            35.25
март 2026                   194            34.89
нояб. 2025                  190            34.17
янв. 2025                   189            33.99
февр. 2025                  189            33.99
окт. 2025                   187            33.63
авг. 2025                   184            33.09
сент. 2025                  169            30.40
авг. 2024                   168            30.22
дек. 2024                   168            30.22
нояб. 2024                  152            27.34
окт. 2024                   133            23.92
сент. 2024                  120            21.58
Номенклатура.Код              2             0.36
Кратность                     2             0.36
Артикул                       2             0.36
Номенклатура                  1             0.18

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1

ПРОПУСКИ:

             missing_count  missing_percent
Unnamed: 11             19            86.36
Unnamed: 14             18            81.82
Unnamed: 0              18            81.82
Unnamed: 12             15            68.18
Unnamed: 13             14            63.64
Unnamed: 10              5            22.73
Unnamed: 2               4            18.18
Unnamed: 3               4            18.18
Unnamed: 6               4            18.18
Unnamed: 4               4            18.18
Unnamed: 5               4            18.18
Unnamed: 7               4            18.18
Unnamed: 9               4            18.18
Unnamed: 8               4            18.18
Unnamed: 1               3            13.64

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1

ПРОПУСКИ:

             missing_count  missing_percent
Unnamed: 0              18            81.82
Unnamed: 14             18            81.82
Unnamed: 12             14            63.64
Unnamed: 13             13            59.09
Unnamed: 10              5            22.73
Unnamed: 11              5            22.73
Unnamed: 2               4            18.18
Unnamed: 3               4            18.18
Unnamed: 6               4            18.18
Unnamed: 4               4            18.18
Unnamed: 5               4            18.18
Unnamed: 7               4            18.18
Unnamed: 9               4            18.18
Unnamed: 8               4            18.18
Unnamed: 1               3            13.64

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet

ПРОПУСКИ:

             missing_count  missing_percent
Unnamed: 57            498           100.00
Unnamed: 58            498           100.00
Unnamed: 55            498           100.00
Unnamed: 56            498           100.00
Unnamed: 53            497            99.80
Unnamed: 59            497            99.80
Unnamed: 6             214            42.97
Unnamed: 8             214            42.97
Unnamed: 7             214            42.97
Unnamed: 9             214            42.97
Unnamed: 10            193            38.76
Unnamed: 11            193            38.76
Unnamed: 12            193            38.76
Unnamed: 13             21             4.22
Unnamed: 14             20             4.02
Unnamed: 17             20             4.02
Unnamed: 16             20             4.02
Unnamed: 15             20             4.02
Unnamed: 20             11             2.21
Unnamed: 21             11             2.21
Unnamed: 22             11             2.21
Unnamed: 18              1             0.20
Unnamed: 19              1             0.20
Unnamed: 24              1             0.20
Unnamed: 23              1             0.20
Unnamed: 25              1             0.20
Unnamed: 26              1             0.20
Unnamed: 32              1             0.20
Unnamed: 31              1             0.20
Unnamed: 30              1             0.20
Unnamed: 29              1             0.20
Unnamed: 28              1             0.20
Unnamed: 27              1             0.20
Unnamed: 33              1             0.20
Unnamed: 34              1             0.20

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

ПРОПУСКИ:

             missing_count  missing_percent
Unnamed: 11             19            86.36
Unnamed: 14             18            81.82
Unnamed: 0              18            81.82
Unnamed: 12             15            68.18
Unnamed: 13             14            63.64
Unnamed: 10              5            22.73
Unnamed: 2               4            18.18
Unnamed: 3               4            18.18
Unnamed: 6               4            18.18
Unnamed: 4               4            18.18
Unnamed: 5               4            18.18
Unnamed: 7               4            18.18
Unnamed: 9               4            18.18
Unnamed: 8               4            18.18
Unnamed: 1               3            13.64

In [7]:
for name, df in datasets.items():

    print("\n" + "=" * 120)
    print(name)

    info = []

    for col in df.columns:
        info.append({
            "column": col,
            "dtype": str(df[col].dtype),
            "unique": df[col].nunique(dropna=True),
            "missing": df[col].isna().sum()
        })

    display(pd.DataFrame(info))

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1

             column    dtype  unique  missing
0                 №  float64     554        2
1      Номенклатура      str     555        1
2  Номенклатура.Код      str     554        2
3           Артикул      str     554        2
4         Кратность  float64      32        2

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1

         column    dtype  unique  missing
0          Дата      str   26955        0
1         Номер  float64   25880        1
2      Документ      str   27099        1
3           Код      str     565        1
4  Номенклатура      str     565        1
5           Ед.      str       1        1
6         Склад      str       1        1
7    Количество  float64     591       13

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1

              column    dtype  unique  missing
0                  №  float64     701        2
1       Номенклатура      str     701        2
2   Номенклатура.Код      str     701        2
3             Ед.изм      str       1        2
4          янв. 2024  float64     169      337
5         февр. 2024  float64     150      346
6          март 2024  float64     189      337
7          апр. 2024  float64     222      333
8           май 2024  float64     277      330
9          июнь 2024  float64     272      321
10         июль 2024  float64     265      319
11         авг. 2024  float64     302      228
12        сент. 2024  float64     323       83
13         окт. 2024  float64     333       73
14        нояб. 2024  float64     333       61
15         дек. 2024  float64     341       55
16         янв. 2025  float64     347       52
17        февр. 2025  float64     334      111
18         март 2025  float64     326      111
19         апр. 2025  float64     340      115
20          май 2025  float64     348      106
21         июнь 2025  float64     342       92
22         июль 2025  float64     339       91
23         авг. 2025  float64     331       89
24        сент. 2025  float64     325       91
25         окт. 2025  float64     324       91
26        нояб. 2025  float64     316      102
27         дек. 2025  float64     311      126
28         янв. 2026  float64     296      128
29        февр. 2026  float64     283      129
30         март 2026  float64     282      134
31         апр. 2026  float64     282      134
32          май 2026  float64     278      130
33         июнь 2026  float64     271      136
34         июль 2026  float64     259      133
35         авг. 2026  float64     260      138
36        сент. 2026  float64     243      137

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

              column    dtype  unique  missing
0       Номенклатура      str     555        1
1   Номенклатура.Код      str     554        2
2            Артикул      str     554        2
3          Кратность  float64      33        2
4          янв. 2024   object      97      331
5         февр. 2024   object     107      318
6          март 2024   object     139      286
7          апр. 2024   object     156      268
8           май 2024   object     163      266
9          июнь 2024   object     152      261
10         июль 2024   object     153      268
11         авг. 2024   object     174      168
12        сент. 2024   object     191      120
13         окт. 2024   object     172      133
14        нояб. 2024   object     170      152
15         дек. 2024   object     185      168
16         янв. 2025   object     146      189
17        февр. 2025   object     168      189
18         март 2025   object     158      205
19         апр. 2025   object     157      199
20          май 2025   object     147      220
21         июнь 2025   object     154      197
22         июль 2025   object     163      202
23         авг. 2025   object     164      184
24        сент. 2025   object     161      169
25         окт. 2025   object     145      187
26        нояб. 2025   object     136      190
27         дек. 2025   object     145      196
28         янв. 2026   object     121      243
29        февр. 2026   object     123      237
30         март 2026   object     138      194
31         апр. 2026   object     135      232
32          май 2026   object     127      239
33         июнь 2026   object     134      222
34         июль 2026   object     129      229
35         авг. 2026   object     138      205
36        сент. 2026   object     123      238
37             Итого   object     415        0

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1

         column   dtype  unique  missing
0    Unnamed: 0  object       4       18
1    Unnamed: 1  object      18        3
2    Unnamed: 2  object      17        4
3    Unnamed: 3  object      18        4
4    Unnamed: 4  object      18        4
5    Unnamed: 5  object      17        4
6    Unnamed: 6  object      18        4
7    Unnamed: 7  object      18        4
8    Unnamed: 8  object      15        4
9    Unnamed: 9  object      16        4
10  Unnamed: 10  object      15        5
11  Unnamed: 11  object       3       19
12  Unnamed: 12  object       7       15
13  Unnamed: 13  object       8       14
14  Unnamed: 14  object       4       18

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1

         column   dtype  unique  missing
0    Unnamed: 0  object       4       18
1    Unnamed: 1  object      18        3
2    Unnamed: 2  object      17        4
3    Unnamed: 3  object      18        4
4    Unnamed: 4  object      18        4
5    Unnamed: 5  object      17        4
6    Unnamed: 6  object      18        4
7    Unnamed: 7  object      18        4
8    Unnamed: 8  object      15        4
9    Unnamed: 9  object      16        4
10  Unnamed: 10  object      15        5
11  Unnamed: 11  object      17        5
12  Unnamed: 12  object       8       14
13  Unnamed: 13  object       9       13
14  Unnamed: 14  object       4       18

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet

         column    dtype  unique  missing
0    Unnamed: 0   object     498        0
1    Unnamed: 1      str     498        0
2    Unnamed: 2      str     498        0
3    Unnamed: 3      str     498        0
4    Unnamed: 4   object       7        0
5    Unnamed: 5   object     494        0
6    Unnamed: 6   object      88      214
7    Unnamed: 7   object      96      214
8    Unnamed: 8   object     129      214
9    Unnamed: 9   object     145      214
10  Unnamed: 10   object     155      193
11  Unnamed: 11   object     148      193
12  Unnamed: 12   object     150      193
13  Unnamed: 13   object     165       21
14  Unnamed: 14   object     186       20
15  Unnamed: 15   object     164       20
16  Unnamed: 16   object     165       20
17  Unnamed: 17   object     182       20
18  Unnamed: 18   object     317        1
19  Unnamed: 19   object     317        1
20  Unnamed: 20   object     142       11
21  Unnamed: 21   object     163       11
22  Unnamed: 22   object     156       11
23  Unnamed: 23   object     156        1
24  Unnamed: 24   object     146        1
25  Unnamed: 25   object     154        1
26  Unnamed: 26   object     164        1
27  Unnamed: 27   object     160        1
28  Unnamed: 28   object     159        1
29  Unnamed: 29   object     144        1
30  Unnamed: 30   object     134        1
31  Unnamed: 31   object     142        1
32  Unnamed: 32   object     122        1
33  Unnamed: 33   object     125        1
34  Unnamed: 34   object     140        1
35  Unnamed: 35   object     133        0
36  Unnamed: 36   object     128        0
37  Unnamed: 37   object     135        0
38  Unnamed: 38   object     130        0
39  Unnamed: 39   object     138        0
40  Unnamed: 40   object     127        0
41  Unnamed: 41   object     317        0
42  Unnamed: 42   object     317        0
43  Unnamed: 43   object     329        0
44  Unnamed: 44   object     344        0
45       СКЛАДЫ   object       5        0
46  Unnamed: 46   object       5        0
47  Unnamed: 47   object       2        0
48  Unnamed: 48   object      95        0
49  Unnamed: 49   object     223        0
50  Unnamed: 50   object      46        0
51  Unnamed: 51   object     225        0
52  Unnamed: 52   object     456        0
53  Unnamed: 53      str       1      497
54  Unnamed: 54   object       8        0
55  Unnamed: 55  float64       0      498
56  Unnamed: 56  float64       0      498
57  Unnamed: 57  float64       0      498
58  Unnamed: 58  float64       0      498
59  Unnamed: 59      str       1      497

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

         column   dtype  unique  missing
0    Unnamed: 0  object       4       18
1    Unnamed: 1  object      18        3
2    Unnamed: 2  object      17        4
3    Unnamed: 3  object      18        4
4    Unnamed: 4  object      18        4
5    Unnamed: 5  object      17        4
6    Unnamed: 6  object      18        4
7    Unnamed: 7  object      18        4
8    Unnamed: 8  object      15        4
9    Unnamed: 9  object      16        4
10  Unnamed: 10  object      15        5
11  Unnamed: 11  object       3       19
12  Unnamed: 12  object       7       15
13  Unnamed: 13  object       8       14
14  Unnamed: 14  object       4       18

In [8]:
for name, df in datasets.items():

    print("\n" + "=" * 120)
    print(name)

    for col in df.columns:

        values = (
            df[col]
            .dropna()
            .unique()[:10]
        )

        print(f"\n{col}:")
        print(values)

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1

№:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Номенклатура:
<StringArray>
[' S174  (1кл, инд с/у 16А, IP44) Переключатель "Wessen 59" ВС 616-157Б-18 (60) !!!',                        ' S179   2кл с/у 16А  "Wessen 59" ВС 510-252-18 (10/60) !!!',
       ' S183  Переключатель 1кл, с инд.,с/у 16А "Wessen 59" ВС 616-157-18 (60) !!!',                        ' S184  Диммер (с/у 600Вт) "Wessen 59" ВПП-5С2-18(2/16) !!!',
                                ' S185 роз-ТВ. с\у  "Wessen 59" РТС 151-18 (60) !!!',                        ' S186  с/у. з/ш 16А  "Wessen 59"  РС 16-151-18 (10/60) !!!',
                      ' S187 с/у. з/ш. з/к.16А "Wessen 59" РС 16-152-18 (10/60) !!!',                    ' S188   с/у. з/ш, 2-я 16А  "Wessen 59" РС 16-254-18 (6/36) !!!',
                ' S189  с/у. з/ш, з,к, 2-я 16А  "Wessen 59" РС 16-255-18 (6/36) !!!',              ' S190  с/у. з/ш. з/к.16А, IP44 "Wessen 59" РС 16-152Б-18 (10/60) !!!']
Length: 10, dtype: str

Номенклатура.Код:
<StringArray>
['030200128_', '030200382_', '030200127_', '030200141_', '030200096_', '030200072_', '030200093_', '030200135_', '030200136_', '030200134_']
Length: 10, dtype: str

Артикул:
<StringArray>
['VS616-157B-18', 'VS510-252-18', 'VS616-157-18', 'SR-5S2-18', 'RTS-151-18', 'RS16-151-18', 'RS16-152-18', 'RS16-254-18', 'RS16-255-18', 'RS16-152B-18']
Length: 10, dtype: str

Кратность:
[  1.  20.  12.   6.  10. 175. 108.  72.  84. 100.]

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1

Дата:
<StringArray>
['18.01.2023 16:00:11', '09.06.2023 17:29:41', '17.11.2023 14:51:23', '17.11.2023 15:02:40', '26.12.2023 17:04:12', '16.02.2024 13:20:41', '01.03.2024 14:58:15', '03.05.2024 12:33:58',
 '23.08.2024 17:08:27', '02.09.2024 10:03:18']
Length: 10, dtype: str

Номер:
[2.00000040e+10 2.00000526e+10 2.00001173e+10 2.00001173e+10
 2.00001329e+10 2.00000166e+10 2.00000208e+10 2.00000448e+10
 2.00000914e+10 2.00000944e+10]

Документ:
<StringArray>
['Расходная накладная 20000004016 от 18.01.2023', 'Расходная накладная 20000052612 от 09.06.2023', 'Расходная накладная 20000117295 от 17.11.2023', 'Расходная накладная 20000117283 от 17.11.2023',
 'Расходная накладная 20000132885 от 26.12.2023', 'Расходная накладная 20000016557 от 16.02.2024', 'Расходная накладная 20000020776 от 01.03.2024', 'Расходная накладная 20000044772 от 03.05.2024',
 'Расходная накладная 20000091369 от 23.08.2024', 'Расходная накладная 20000094396 от 02.09.2024']
Length: 10, dtype: str

Код:
<StringArray>
['300200445_', '300200299_', '300200290_', '300200448_', '020100162_', '300200307_', '300200283_', '300200446_', '300200784_', '300200785_']
Length: 10, dtype: str

Номенклатура:
<StringArray>
[                                 'А409 Рамка 5-ная "ATLAS" алюминий ATN305 (5)',      'S396 Роз. 2-ная с/у 16А с з/к з/ш со сдвиж.крыш."ATLAS" белый ATN128 (6)',
          'S392 Переключ. 1 кл с инд 10А с/у б/рамки  "ATLAS" белый ATN163 (20)',    'А393 Перекрест. переключ. 1 кл 10А с/у б/рамки "ATLAS" алюминий ATN371 (5)',
 'K077 Перекрест.переключ. 1 кл 10А с/у б/рамки "ATLAS", КАРБОН -  ATN1071 (2) ',                                     'S409 Рамка 5-ная "ATLAS" белый (5) ATN105',
                'S385 Выкл 1 кл с инд 10А с/у б/рамки "ATLAS" белый ATN113 (20)',              'А414 Переключ. 2 кл 10А с/у б/рамки "ATLAS" алюминий ATN365 (10)',
            'G001 Роз. с з/к 16А механизм "ARTGALLERY" алюминий GAL0343 (10)   ',                     'G002 Выкл. 1 кл 10А "ARTGALLERY" алюминий GAL0311 (10)   ']
Length: 10, dtype: str

Ед.:
<StringArray>
['шт']
Length: 1, dtype: str

Склад:
<StringArray>
['Алматы']
Length: 1, dtype: str

Количество:
[-10.  -2.  -5. -30. -20.  -9.  -6.  -4. -17. -15.]

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1

№:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Номенклатура:
<StringArray>
[ ' AtlasDesign Розетка 1я Алюминий без  з/к без штор. 16А, в сборе, ATN000340 (10)', ' S174  (1кл, инд с/у 16А, IP44) Переключатель "Wessen 59" ВС 616-157Б-18 (60) !!!',
                           ' S175 2кл инд с/у 16А "Wessen 59" ВС 516-251-18 (10/60)',                              ' S1766 1кл с/у 16А "Wessen 59" ВС 116-154-18 (10/60)',
                            ' S178  3кл с/у 16А  "Wessen 59" ВС 0516-351-18 (10/60)',                        ' S179   2кл с/у 16А  "Wessen 59" ВС 510-252-18 (10/60) !!!',
           ' S181 1кл с/у 16А Переключатель "Wessen 59" ВС 616-156-1-86 (10/60) !!!',             ' S181 1кл с/у 16А Переключатель "Wessen 59" ВС 616-156-18 (10/60) !!!',
       ' S182   1кл с/у 16А, IP44 Переключатель "Wessen 59" ВС 616-156Б-18 (60) !!!',       ' S183  Переключатель 1кл, с инд.,с/у 16А "Wessen 59" ВС 616-157-18 (60) !!!']
Length: 10, dtype: str

Номенклатура.Код:
<StringArray>
['300200635_', '030200128_', '030200092_', '030200073_', '300100004_', '030200382_', '030200345', '030200125_', '030200126_', '030200127_']
Length: 10, dtype: str

Ед.изм:
<StringArray>
['шт']
Length: 1, dtype: str

янв. 2024:
[1.000e+00 3.000e+00 2.280e+02 2.000e+00 4.000e+00 1.280e+02 2.080e+02
 7.100e+01 1.073e+03 9.000e+00]

февр. 2024:
[1.000e+00 3.000e+00 2.270e+02 2.000e+00 4.000e+00 1.260e+02 1.740e+02
 2.080e+02 5.100e+01 1.063e+03]

март 2024:
[1.000e+00 3.000e+00 2.230e+02 2.000e+00 1.230e+02 1.520e+02 2.050e+02
 4.800e+01 1.061e+03 9.000e+00]

апр. 2024:
[1.000e+00 3.000e+00 2.220e+02 2.000e+00 1.210e+02 1.500e+02 2.000e+02
 4.800e+01 1.061e+03 9.000e+00]

май 2024:
[1.000e+00 3.000e+00 2.210e+02 2.000e+00 1.150e+02 1.500e+02 1.990e+02
 4.600e+01 1.061e+03 9.000e+00]

июнь 2024:
[1.000e+00 3.000e+00 2.120e+02 2.000e+00 8.900e+01 1.480e+02 1.720e+02
 4.000e+01 1.061e+03 9.000e+00]

июль 2024:
[1.000e+00 3.000e+00 2.080e+02 2.000e+00 8.800e+01 8.100e+01 1.720e+02
 2.000e+01 1.061e+03 7.000e+00]

авг. 2024:
[1.000e+00 1.500e+01 9.000e+00 2.050e+02 2.000e+00 1.230e+02 1.182e+03
 1.046e+03 1.720e+02 2.030e+02]

сент. 2024:
[1.000e+00 1.500e+01 9.000e+00 1.310e+02 2.000e+00 1.230e+02 1.182e+03
 1.030e+03 1.720e+02 2.030e+02]

окт. 2024:
[1.000e+00 1.500e+01 9.000e+00 1.650e+02 2.000e+00 1.230e+02 1.182e+03
 1.030e+03 1.720e+02 2.030e+02]

нояб. 2024:
[1.000e+00 1.500e+01 9.000e+00 1.600e+02 2.000e+00 1.230e+02 1.182e+03
 1.030e+03 1.720e+02 2.030e+02]

дек. 2024:
[1.000e+00 1.500e+01 9.000e+00 1.600e+02 2.000e+00 1.230e+02 1.182e+03
 1.030e+03 1.720e+02 2.030e+02]

янв. 2025:
[1.000e+00 1.500e+01 5.000e+00 1.580e+02 2.000e+00 1.230e+02 1.182e+03
 1.022e+03 1.470e+02 2.000e+02]

февр. 2025:
[1.000e+00 3.000e+00 1.580e+02 2.000e+00 1.230e+02 1.175e+03 1.021e+03
 1.470e+02 2.000e+02 1.232e+03]

март 2025:
[1.000e+00 3.000e+00 1.580e+02 2.000e+00 1.230e+02 1.175e+03 1.021e+03
 1.470e+02 2.000e+02 1.232e+03]

апр. 2025:
[1.000e+00 3.000e+00 1.580e+02 2.000e+00 1.230e+02 1.175e+03 1.021e+03
 1.470e+02 2.000e+02 1.232e+03]

май 2025:
[1.000e+00 3.000e+00 1.580e+02 2.000e+00 1.230e+02 1.175e+03 1.021e+03
 1.470e+02 1.990e+02 1.232e+03]

июнь 2025:
[7.000e+00 1.000e+00 3.000e+00 1.580e+02 1.000e+01 2.000e+00 6.000e+00
 1.800e+01 1.230e+02 1.232e+03]

июль 2025:
[7.000e+00 1.000e+00 3.000e+00 1.580e+02 1.000e+01 6.000e+00 1.800e+01
 1.230e+02 1.308e+03 1.331e+03]

авг. 2025:
[5.000e+00 7.000e+00 3.000e+00 1.000e+00 1.670e+02 1.000e+01 6.000e+00
 1.800e+01 1.308e+03 1.331e+03]

сент. 2025:
[5.000e+00 7.000e+00 3.000e+00 1.000e+00 1.640e+02 1.000e+01 6.000e+00
 1.800e+01 1.289e+03 1.331e+03]

окт. 2025:
[5.000e+00 7.000e+00 3.000e+00 1.000e+00 1.610e+02 1.000e+01 6.000e+00
 1.800e+01 1.272e+03 1.330e+03]

нояб. 2025:
[3.000e+00 7.000e+00 1.000e+00 1.520e+02 1.000e+01 2.000e+00 1.800e+01
 1.256e+03 1.330e+03 2.470e+02]

дек. 2025:
[1.000e+00 1.420e+02 1.000e+01 1.252e+03 1.288e+03 2.440e+02 4.730e+02
 1.271e+03 2.200e+01 1.460e+02]

янв. 2026:
[  12.    4.  127.   10.   16.   24.  336.  206.  219. 1080.]

февр. 2026:
[  12.    4.  118.   10.   14.   24.   56.  204.  136. 1076.]

март 2026:
[  12.    4.  111.   10.   24.   22.  188.  130. 1055.   21.]

апр. 2026:
[  12.    4.  107.   10.   24.  167.  125. 1055.   21.  146.]

май 2026:
[ 12.   4.  88.  10.  23.   3. 154.  90. 972.  20.]

июнь 2026:
[ 12.   4.  43.  10.   3. 106.  78. 936.  20. 146.]

июль 2026:
[ 12.   4.  39.  10.   3.  63.  55. 925.  20. 146.]

авг. 2026:
[ 12.   4.  34.  10.   3.  17.  55. 898.  20. 146.]

сент. 2026:
[ 12.   4.  34.  10.   3.  30. 868.  20. 146.  47.]

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

Номенклатура:
<StringArray>
[' S174  (1кл, инд с/у 16А, IP44) Переключатель "Wessen 59" ВС 616-157Б-18 (60) !!!',                        ' S179   2кл с/у 16А  "Wessen 59" ВС 510-252-18 (10/60) !!!',
       ' S183  Переключатель 1кл, с инд.,с/у 16А "Wessen 59" ВС 616-157-18 (60) !!!',                        ' S184  Диммер (с/у 600Вт) "Wessen 59" ВПП-5С2-18(2/16) !!!',
                                ' S185 роз-ТВ. с\у  "Wessen 59" РТС 151-18 (60) !!!',                        ' S186  с/у. з/ш 16А  "Wessen 59"  РС 16-151-18 (10/60) !!!',
                      ' S187 с/у. з/ш. з/к.16А "Wessen 59" РС 16-152-18 (10/60) !!!',                    ' S188   с/у. з/ш, 2-я 16А  "Wessen 59" РС 16-254-18 (6/36) !!!',
                ' S189  с/у. з/ш, з,к, 2-я 16А  "Wessen 59" РС 16-255-18 (6/36) !!!',              ' S190  с/у. з/ш. з/к.16А, IP44 "Wessen 59" РС 16-152Б-18 (10/60) !!!']
Length: 10, dtype: str

Номенклатура.Код:
<StringArray>
['030200128_', '030200382_', '030200127_', '030200141_', '030200096_', '030200072_', '030200093_', '030200135_', '030200136_', '030200134_']
Length: 10, dtype: str

Артикул:
<StringArray>
['VS616-157B-18', 'VS510-252-18', 'VS616-157-18', 'SR-5S2-18', 'RTS-151-18', 'RS16-151-18', 'RS16-152-18', 'RS16-254-18', 'RS16-255-18', 'RS16-152B-18']
Length: 10, dtype: str

Кратность:
[  0.  20.  12.   6.  10. 175. 108.  72.  84. 100.]

янв. 2024:
['Количество' 1 2 34 20 10 3 596 54 814]

февр. 2024:
['Количество' 4 2 1 22 3 229 20 52 8156]

март 2024:
['Количество' 1 2 5 347 109 359 1109 80 4511]

апр. 2024:
['Количество' 1 6 2 824 1487 2538 56 17153 42968]

май 2024:
['Количество' 9 26 2 27 6 1433 1257 3320 3]

июнь 2024:
['Количество' 4 1 67 20 2 28 1162 50 1217]

июль 2024:
['Количество' 3 843 50 1978 3399 31 251 17311 40484]

авг. 2024:
['Количество' 74 16 5 2 237 15 2181 2723 250]

сент. 2024:
['Количество' -34 1 776 71 1444 2476 30 216 16565]

окт. 2024:
['Количество' 5 1211 20 1525 2858 2 201 22804 42301]

нояб. 2024:
['Количество' 1005 6 1505 1388 46 142 17450 40967 14065]

дек. 2024:
['Количество' 2 8 1 373 50 872 1186 10 3]

янв. 2025:
['Количество' 2 1 579 149 747 5141 16307 53478 20124]

февр. 2025:
['Количество' 383 111 1307 3492 10 34 22560 43751 14561]

март 2025:
['Количество' 944 108 906 3656 10 1814 21882 54311 15620]

апр. 2025:
['Количество' 1 614 1229 3658 191 25710 52084 19797 104]

май 2025:
['Количество' 480 1883 3963 1395 17627 50676 20724 589 9]

июнь 2025:
['Количество' 3 1 764 2328 5211 40 25136 62934 19636]

июль 2025:
['Количество' 2 120 10 1 581 3 1252 10609 60]

авг. 2025:
['Количество' 3 19 2 621 195 1464 7696 95 361]

сент. 2025:
['Количество' 3 17 1 2 21 959 973 4320 241]

окт. 2025:
['Количество' 2 9 4 16 -4 164 80 1661 2560]

нояб. 2025:
['Количество' 2 3 41 1 265 1287 10940 324 27153]

дек. 2025:
['Количество' 15 134 110 38 100 1 227 892 2129]

янв. 2026:
['Количество' 8 2 278 82 878 860 2278 301 18659]

февр. 2026:
['Количество' 7 14 34 16 6 21 1 1411 736]

март 2026:
['Количество' 4 10 21 5 1586 1267 1574 260 21684]

апр. 2026:
['Количество' 19 1 9 13 35 83 106 1202 3427]

май 2026:
['Количество' 45 20 46 11 35 535 2037 15087 1]

июнь 2026:
['Количество' 4 44 23 11 227 1841 4807 295 29064]

июль 2026:
['Количество' 5 46 27 1232 1635 3680 9 39200 4209]

авг. 2026:
['Количество' 18 24 30 1701 1662 3555 5 36290 3754]

сент. 2026:
['Количество' 4 5 64 398 1092 2979 2 186 27768]

Итого:
['Количество' 4 196 18 122 263 635 286 363 294]

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1

Unnamed: 0:
['год' 2024 2025 2026]

Unnamed: 1:
['янв' 24596427 60612221 51463402 'Сезонность по годам' 'Месяц' 'фев'
 'мар' 'апр' 'май']

Unnamed: 2:
['фев' 22395512 70526214 57127585 'Продажи 2024' 24596427 44147660
 62276496.32 73462110 68345412]

Unnamed: 3:
['мар' 44147660 62394638.9 49906664.43 'Коэф. сезонности'
 0.37164423323186774 0.33838910363180363 0.6670571806905612
 0.9409781641542341 1.1099892493550028]

Unnamed: 4:
['апр' 62276496.32 80289436.03 61255146 'Доля в году' 0.030970352769322314
 0.028199091969316973 0.05558809839088011 0.07841484701285284
 0.09249910411291691]

Unnamed: 5:
['май' 73462110 77227054 59215517 'Продажи 2025' 60612221 70526214
 62394638.9 80289436.03 80386586]

Unnamed: 6:
['июн' 68345412 80386586 68110627 'Коэф. сезонности 2025'
 0.8200591283342988 0.9541914918042389 0.8441745302332236
 1.0862839843010248 1.0448511792211974]

Unnamed: 7:
['июл' 71289315.98 79580845.35 72110849.17 'Доля в году 2025'
 0.0683382606945249 0.07951595765035324 0.0703478775194353
 0.09052366535841873 0.08707093160176645]

Unnamed: 8:
['авг' 91399515.64 85147826.95 70105174.18 'Продажи 2026' 51463402
 57127585 49906664.43 61255146 59215517]

Unnamed: 9:
['сен' 99082123 75393744 45371784.46 'Коэф. сезонности 2026'
 0.8662790769360019 0.9616237885202962 0.8400746455777486
 1.0311026724284575 0.9967697706235613]

Unnamed: 10:
['окт' 88432469 70827551 'Доля в году 2026' 0.09625323077066687
 0.10684708761336624 0.09334162728641651 0.11456696360316196
 0.11075219673595126 0.12738893356808814]

Unnamed: 11:
['ноя' 82883679 72949510]

Unnamed: 12:
['дек' 65881945 71608529.44 'Год' 2024 2025 2026]

Unnamed: 13:
['ИТОГО' 794192664.94 886944156.6700001 534666749.24 'Среднемес.'
 66182722.07833334 73912013.05583334 59407416.58222222]

Unnamed: 14:
['Итого за год' 794192664.94 886944156.6700001 534666749.24]

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1

Unnamed: 0:
['год' 2024 2025 2026]

Unnamed: 1:
['янв' 24596427 60612221 51463402 'Сезонность по годам' 'Месяц' 'фев'
 'мар' 'апр' 'май']

Unnamed: 2:
['фев' 22395512 70526214 57127585 'Продажи 2024' 24596427 44147660
 62276496.32 73462110 68345412]

Unnamed: 3:
['мар' 44147660 62394638.9 49906664.43 'Коэф. сезонности'
 0.37164423323186774 0.33838910363180363 0.6670571806905612
 0.9409781641542341 1.1099892493550028]

Unnamed: 4:
['апр' 62276496.32 80289436.03 61255146 'Доля в году' 0.030970352769322314
 0.028199091969316973 0.05558809839088011 0.07841484701285284
 0.09249910411291691]

Unnamed: 5:
['май' 73462110 77227054 59215517 'Продажи 2025' 60612221 70526214
 62394638.9 80289436.03 80386586]

Unnamed: 6:
['июн' 68345412 80386586 68110627 'Коэф. сезонности 2025'
 0.8200591283342988 0.9541914918042389 0.8441745302332236
 1.0862839843010248 1.0448511792211974]

Unnamed: 7:
['июл' 71289315.98 79580845.35 72110849.17 'Доля в году 2025'
 0.0683382606945249 0.07951595765035324 0.0703478775194353
 0.09052366535841873 0.08707093160176645]

Unnamed: 8:
['авг' 91399515.64 85147826.95 70105174.18 'Продажи 2026' 51463402
 57127585 49906664.43 61255146 59215517]

Unnamed: 9:
['сен' 99082123 75393744 45371784.46 'Коэф. сезонности 2026'
 0.8662790769360019 0.9616237885202962 0.8400746455777486
 1.0311026724284575 0.9967697706235613]

Unnamed: 10:
['окт' 88432469 70827551 'Доля в году 2026' 0.09625323077066687
 0.10684708761336624 0.09334162728641651 0.11456696360316196
 0.11075219673595126 0.12738893356808814]

Unnamed: 11:
['ноя' 82883679 72949510 'СЕЗОННОСТЬ' 0.8431691026351504
 0.9579076401622675 0.8421245879054862 1.058693328364741
 1.0208104749223794 1.1170493933424717]

Unnamed: 12:
['дек' 65881945 71608529.44 'Год' 2024 2025 2026
 'Поправка 2026/2025 (янв-сен)']

Unnamed: 13:
['ИТОГО' 794192664.94 886944156.6700001 534666749.24 'Среднемес.'
 66182722.07833334 73912013.05583334 59407416.58222222 0.9905437156983194]

Unnamed: 14:
['Итого за год' 794192664.94 886944156.6700001 534666749.24]

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet

Unnamed: 0:
['№' 1 2 3 4 5 6 7 8 9]

Unnamed: 1:
<StringArray>
['Артикул поставщика', 'ATN000343', 'ATN000333', 'ATN000330', 'ATN000312', 'ATN000311', 'ATN000313', 'ATN000352', 'ATN000351', 'ATN000353']
Length: 10, dtype: str

Unnamed: 2:
<StringArray>
['Код 1с', '300200428_', '300200442_', 'ATN000330', '300200430_', '300200588_', '300200443_', '300200432_', '300200589_', '300200444_']
Length: 10, dtype: str

Unnamed: 3:
<StringArray>
[                                                              'Наименование',               'A398 Роз. с з/к 16А с/у б/рамки "ATLAS" алюминий ATN343 (10)',
         'A404 USB розетка - 2 порта с/у б/рамки "ATLAS" алюминий ATN333 (1)', 'SO + USB РОЗЕТКА A+A, 5В/2,4А, 2х5В/1,2А, механизм "ATLAS" алюминий ATN330',
                        'А384 Выкл 1 кл 10А с/у "ATLAS" алюминий ATN312 (10)',                  'А3844 Выкл 1 кл 10А механизм "ATLAS" алюминий ATN311 (10)',
         'А385 Выкл 1 кл с инд 10А с/у б/рамки "ATLAS" алюминий ATN313  (10)',                        'А386 Выкл 2 кл 10А с/у "ATLAS" алюминий ATN352 (10)',
                  'А3866 Выкл 2 кл 10А механизм "ATLAS" алюминий ATN351 (10)',          'А387 Выкл 2 кл с инд 10А с/у б/рамки "ATLAS" алюминий ATN353 (10)']
Length: 10, dtype: str

Unnamed: 4:
['Категория 2026' '1' '7' '2' '3' '5' 5]

Unnamed: 5:
['СС реал' 1050.61 0 1286.15 899.75 1585.22 1105.28 1267.41 1633.09
 1554.69]

Unnamed: 6:
['Январь 2024 г.' 346 0 94 10 53 5 11 4 7]

Unnamed: 7:
['Февраль 2024 г.' 335 0 40 4 3 1 2 17 14]

Unnamed: 8:
['Март 2024 г.' 233 0 26 30 10 5 9 1 29]

Unnamed: 9:
['Апрель 2024 г.' 525 0 25 111 30 94 42 7 31]

Unnamed: 10:
['Май 2024 г.' 546 0 119 115 10 61 2 19 39]

Unnamed: 11:
['Июнь 2024 г.' 541 0 62 109 30 17 4 1 24]

Unnamed: 12:
['Июль 2024 г.' 508 0 26 71 5 12 3 1 37]

Unnamed: 13:
['Август 2024 г.' 707 0 24 132 8 27 95 2 4]

Unnamed: 14:
['Сентябрь 2024 г.' 359 0 29 111 26 8 79 13 12]

Unnamed: 15:
['Октябрь 2024 г.' 384 0 26 86 16 49 18 13 24]

Unnamed: 16:
['Ноябрь 2024 г.' 253 0 70 55 10 28 13 6 2]

Unnamed: 17:
['Декабрь 2024 г.' 530 0 -23 119 -25 -12 81 -15 -5]

Unnamed: 18:
['Продажи 2024' 5267 0 518 943 133 359 420 88 68]

Unnamed: 19:
['Ср мес 2024' 438.9166666666667 0 43.166666666666664 78.58333333333333
 11.083333333333334 29.916666666666668 35 7.333333333333333
 5.666666666666667]

Unnamed: 20:
['Январь 2025 г.' 610 0 32 133 1 23 61 15 12]

Unnamed: 21:
['Февраль 2025 г.' 394 0 15 32 20 27 51 9 61]

Unnamed: 22:
['Март 2025 г.' 444 0 3 78 4 39 30 2 23]

Unnamed: 23:
['Апрель 2025 г.' 104 0 20 65 5 36 1 6 18]

Unnamed: 24:
['Май 2025 г.' 589 0 25 107 30 57 73 40 18]

Unnamed: 25:
['Июнь 2025 г.' 413 0 100 131 11 19 -1 3 68]

Unnamed: 26:
['Июль 2025 г.' 379 0 12 77 7 42 17 3 20]

Unnamed: 27:
['Август 2025 г.' 170 0 12 27 5 13 3 9 7]

Unnamed: 28:
['Сентябрь 2025 г.' 806 0 42 75 24 39 30 10 11]

Unnamed: 29:
['Октябрь 2025 г.' 212 0 23 145 3 11 45 2 7]

Unnamed: 30:
['Ноябрь 2025 г.' 353 0 18 67 22 13 55 3 4]

Unnamed: 31:
['Декабрь 2025 г.' 724 0 132 120 11 46 51 22 18]

Unnamed: 32:
['Январь 2026 г.' 111 0 25 17 10 9 2 62 27]

Unnamed: 33:
['Февраль 2026 г.' 152 0 6 28 1 34 10 38 8]

Unnamed: 34:
['Март 2026 г.' 380 0 24 53 4 38 1 16 71]

Unnamed: 35:

In [9]:
for name, df in datasets.items():

    numeric = df.select_dtypes(include=np.number)

    print("\n" + "=" * 120)
    print(name)

    if numeric.empty:
        print("Числовых признаков нет")
        continue

    print("ЧИСЛОВАЯ СТАТИСТИКА:")
    display(numeric.describe().T)

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1
ЧИСЛОВАЯ СТАТИСТИКА:

           count        mean         std  min     25%    50%     75%     max
№          554.0  277.500000  160.070297  1.0  139.25  277.5  415.75   554.0
Кратность  554.0   26.155235  224.870606  1.0    5.00    5.0   10.00  3780.0

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1
ЧИСЛОВАЯ СТАТИСТИКА:

              count          mean           std       min           25%           50%           75%           max
Номер       77312.0  2.018529e+10  1.356913e+09  526019.0  2.000003e+10  2.000007e+10  2.000010e+10  3.000003e+10
Количество  77300.0  1.769076e+02  2.461300e+04    -260.0  2.000000e+00  1.000000e+01  3.000000e+01  6.837478e+06

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
ЧИСЛОВАЯ СТАТИСТИКА:

            count         mean           std  min     25%    50%     75%       max
№           701.0   351.000000    202.505555  1.0  176.00  351.0  526.00     701.0
янв. 2024   366.0   521.871585   4042.877905  1.0    7.00   30.0  120.50   71594.0
февр. 2024  357.0   180.658263    861.994992  1.0    4.00   18.0   85.00   12248.0
март 2024   366.0   369.748634   1210.277044  1.0   10.00   42.0  209.50   15746.0
апр. 2024   370.0   896.970270   5323.606096  1.0   15.00   69.5  333.75   87989.0
май 2024    373.0  2703.195710  16825.764954  1.0   36.00  160.0  807.00  277173.0
июнь 2024   382.0  2319.544503  14774.784414  1.0   36.25  146.5  627.00  248438.0
июль 2024   384.0  1893.924479  12062.787108  1.0   27.00  125.5  521.00  203372.0
авг. 2024   475.0  2057.046316  14618.315602  1.0   24.00  103.0  526.50  274046.0
сент. 2024  620.0  1360.359677  10493.426417  1.0   25.75   77.0  355.00  224194.0
окт. 2024   630.0  1089.666667   7726.696712  1.0   22.00   69.5  310.00  161521.0
нояб. 2024  642.0   826.931464   5545.095804  1.0   23.25   67.0  305.50  115696.0
дек. 2024   648.0   849.464506   5522.776791  1.0   28.75   80.0  321.50  118075.0
янв. 2025   651.0  1165.600614   8580.513026  1.0   32.00   91.0  325.50  183707.0
февр. 2025  592.0  1037.738176   6691.477370  1.0   37.00   98.0  342.50  134016.0
март 2025   592.0   919.787162   5817.512324  1.0   34.00   89.5  314.00  115664.0
апр. 2025   588.0  1090.469388   6340.344728  1.0   37.00  101.0  365.00  120359.0
май 2025    597.0  1632.460637  12035.028456  1.0   37.00   99.0  360.00  250037.0
июнь 2025   611.0  1339.268412   9520.182368  1.0   32.00   92.0  331.50  199124.0
июль 2025   612.0  1073.454248   6730.248202  1.0   30.00   88.0  306.25  136329.0
авг. 2025   614.0  1007.741042   6408.477192  1.0   32.00   89.5  298.50  130563.0
сент. 2025  612.0   959.406863   6833.421041  1.0   29.00   82.0  262.25  139191.0
окт. 2025   612.0   952.496732   7270.946798  1.0   28.75   86.5  259.25  160264.0
нояб. 2025  601.0   938.715474   6917.167337  1.0   31.00   90.0  248.00  142023.0
дек. 2025   577.0   941.343154   7026.266204  1.0   34.00   89.0  243.00  139814.0
янв. 2026   575.0   900.271304   7515.862258  1.0   28.00   80.0  214.50  158392.0
февр. 2026  574.0   691.651568   5561.832890  1.0   27.00   74.0  192.00  119081.0
март 2026   569.0   797.666081   7496.143649  1.0   26.00   74.0  189.00  160838.0
апр. 2026   569.0   839.163445   7650.135263  1.0   26.00   75.0  188.00  161697.0
май 2026    573.0   944.171030   8707.509734  1.0   25.00   74.0  188.00  179594.0
июнь 2026   567.0   711.266314   6342.269979  1.0   23.00   70.0  177.00  133507.0
июль 2026   570.0   642.029825   5386.752136  1.0   20.00   61.5  160.75  109510.0
авг. 2026   565.0   695.536283   6336.316638  1.0   23.00   62.0  145.00  132895.0
сент. 2026  566.0   536.959364   4461.606694  1.0   19.00   56.5  131.00   93532.0

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1
ЧИСЛОВАЯ СТАТИСТИКА:

           count       mean         std  min  25%  50%   75%     max
Кратность  554.0  26.108303  224.875965  0.0  5.0  5.0  10.0  3780.0

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
Числовых признаков нет

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1
Числовых признаков нет

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
ЧИСЛОВАЯ СТАТИСТИКА:

             count  mean  std  min  25%  50%  75%  max
Unnamed: 55    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Unnamed: 56    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Unnamed: 57    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Unnamed: 58    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1
Числовых признаков нет

In [10]:
for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(
        f"{name}: "
        f"{duplicates} полных дубликатов "
        f"({duplicates / len(df) * 100:.2f}%)"
        if len(df) > 0
        else f"{name}: пустая таблица"
    )

MOQ SystemElectric.xlsx | Лист_1: 0 полных дубликатов (0.00%)
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1: 0 полных дубликатов (0.00%)
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1: 1 полных дубликатов (0.14%)
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1: 0 полных дубликатов (0.00%)
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1: 2 полных дубликатов (9.09%)
Сезонность SystemElectric 2024-2026.xlsx | Лист1: 2 полных дубликатов (9.09%)
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet: 0 полных дубликатов (0.00%)
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1: 2 полных дубликатов (9.09%)

In [11]:
for name, df in datasets.items():

    print("\n" + "=" * 120)
    print(name)

    for col in df.columns:

        col_name = str(col).lower()

        if (
            "дата" in col_name
            or "date" in col_name
            or "период" in col_name
            or "месяц" in col_name
        ):
            print(f"\nВозможная дата: {col}")

            print("Тип:", df[col].dtype)
            print("Примеры:")

            display(df[[col]].head(10))

========================================================================================================================
MOQ SystemElectric.xlsx | Лист_1

========================================================================================================================
Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1

Возможная дата: Дата
Тип: str
Примеры:

                  Дата
0  18.01.2023 16:00:11
1  09.06.2023 17:29:41
2  17.11.2023 14:51:23
3  17.11.2023 15:02:40
4  26.12.2023 17:04:12
5  26.12.2023 17:04:12
6  16.02.2024 13:20:41
7  01.03.2024 14:58:15
8  03.05.2024 12:33:58
9  23.08.2024 17:08:27

========================================================================================================================
Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

========================================================================================================================
Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1

========================================================================================================================
Сезонность SystemElectric 2024-2026.xlsx | Лист1

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet

========================================================================================================================
Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

In [12]:
column_locations = {}

for name, df in datasets.items():

    for col in df.columns:

        normalized = str(col).strip().lower()

        if normalized not in column_locations:
            column_locations[normalized] = []

        column_locations[normalized].append(name)


print("СТОЛБЦЫ, ВСТРЕЧАЮЩИЕСЯ В НЕСКОЛЬКИХ ТАБЛИЦАХ:\n")

for col, tables in column_locations.items():

    if len(tables) > 1:

        print(f"\n{col}")

        for table in tables:
            print("  →", table)

СТОЛБЦЫ, ВСТРЕЧАЮЩИЕСЯ В НЕСКОЛЬКИХ ТАБЛИЦАХ:


№
  → MOQ SystemElectric.xlsx | Лист_1
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1

номенклатура
  → MOQ SystemElectric.xlsx | Лист_1
  → Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

номенклатура.код
  → MOQ SystemElectric.xlsx | Лист_1
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

артикул
  → MOQ SystemElectric.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

кратность
  → MOQ SystemElectric.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

янв. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

февр. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

март 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

апр. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

май 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июнь 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июль 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

авг. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

сент. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

окт. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

нояб. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

дек. 2024
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

янв. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

февр. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

март 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

апр. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

май 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июнь 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июль 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

авг. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

сент. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

окт. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

нояб. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

дек. 2025
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

янв. 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

февр. 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

март 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

апр. 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

май 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июнь 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

июль 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

авг. 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

сент. 2026
  → Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1

unnamed: 0
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 1
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 2
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 3
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 4
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 5
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 6
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 7
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 8
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 9
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 10
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 11
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 12
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 13
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

unnamed: 14
  → Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1
  → Сезонность SystemElectric 2024-2026.xlsx | Лист1
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet
  → Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1

In [13]:
summary = []

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

    summary.append({
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": ", ".join(map(str, df.columns)),
        "numeric_columns": ", ".join(map(str, numeric_cols)),
        "missing_cells": int(df.isna().sum().sum()),
        "duplicates": int(df.duplicated().sum())
    })

summary_df = pd.DataFrame(summary)

display(summary_df)

,table,rows,columns,column_names,numeric_columns,missing_cells,duplicates
0,MOQ SystemElectric.xlsx | Лист_1,556,5,"№, Номенклатура, Номенклатура.Код, Артикул, Кратность","№, Кратность",9,0
1,Динамика продаж_Syseme Electric_2025-2026.xlsx | Лист_1,77313,8,"Дата, Номер, Документ, Код, Номенклатура, Ед., Склад, Количество","Номер, Количество",19,0
2,Ежемесячные остатки SystemElectric 2024-2026.xlsx | Лист_1,703,37,"№, Номенклатура, Номенклатура.Код, Ед.изм, янв. 2024, февр. 2024, март 2024, апр. 2024, май 2024...","№, янв. 2024, февр. 2024, март 2024, апр. 2024, май 2024, июнь 2024, июль 2024, авг. 2024, сент....",5207,1
3,Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист_1,556,38,"Номенклатура, Номенклатура.Код, Артикул, Кратность, янв. 2024, февр. 2024, март 2024, апр. 2024,...",Кратность,7112,0
4,Ежемесячные продажи в кол-м выражении SystemElectric 2024-2026.xlsx | Лист1,22,15,"Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, ...",,124,2
5,Сезонность SystemElectric 2024-2026.xlsx | Лист1,22,15,"Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, ...",,108,2
6,Товар в пути_SystemElectric на 22.09.2026.xlsx | TDSheet,498,60,"Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, ...","Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58",4569,0
7,Товар в пути_SystemElectric на 22.09.2026.xlsx | Лист1,22,15,"Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, ...",,124,2